<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <Target Name="CopyDLLs" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)$(ProjectName).dll" DestinationFolder="$(MD_NET6_DIRECTORY)\Mods" />
    <Message Text="Copied DLL -&gt; $(MD_NET6_DIRECTORY)\Mods\$(ProjectName).dll" Importance="High" />
  </Target>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\net6\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Iced">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\SupportModules\Iced.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cpp">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppAssemblyGenerator">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyGenerator.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\SupportModules\Il2CppInterop.Common.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.HarmonySupport">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\SupportModules\Il2CppInterop.HarmonySupport.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\net6\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\SupportModules\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\Il2CppAssemblyGenerator\MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\Il2CppAssemblyGenerator\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="Preload">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\SupportModules\Preload.dll</HintPath>
    </Reference>
    <Reference Include="Tomlet">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Dependencies\SupportModules\Tomlet.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
	<Reference Include="UnityEngine.ImageConversionModule">
		<HintPath>E:\steam\steamapps\common\Muse Dash\MelonLoader\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll</HintPath>
	</Reference>
  </ItemGroup>

</Project>
